-- Insert a set of records.
INSERT INTO department (name) VALUES ("Front Office");
INSERT INTO department (name) VALUES ("Software");
INSERT INTO department (name) VALUES ("Support");
INSERT INTO department (name) VALUES ("OPS");
INSERT INTO role (title, salary, dept_id) VALUES ("Chief Executive officer", 21032, 1);
INSERT INTO role (title, salary, dept_id) VALUES ("Program manager", 1171, 1);
INSERT INTO role (title, salary, dept_id) VALUES ("Web Developer, Sr", 25, 2);
INSERT INTO role (title, salary, dept_id) VALUES ("Web Developer, Jr", 23, 2);
INSERT INTO role (title, salary, dept_id) VALUES ("Data Dev, Sr", 13, 3);
INSERT INTO role (title, salary, dept_id) VALUES ("Data Dev, Jr", 11, 3);
INSERT INTO role (title, salary, dept_id) VALUES ("Technical Writer", 35, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Business Analyst", 14, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Network Engineer, Sr", 7, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Network Engineer, Jr", 1, 4);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Mitch", "Wales", 1,1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Sally", "Turner", 2, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Fredrick", "Jonas", 3, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Buster", "Brownie", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Sophie", "Turner", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Alice", "Jones", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Kat", "Smith", 5, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Bob", "Tumbro", 6, 7);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Doris", "Day", 6, 7);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Elaine", "Windsor", 7, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Frank", "Ferret", 8, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Gerry", "Gerbil", 8, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Harry", "Styles", 9, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Inga", "Stark", 9, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Jerry", "Garcia", 9, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Keri", "Kerr", 10, 10);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Leonard", "Johns", 10, 10);